const DAILY = "DAILY";
const WEEKLY = "WEEKLY";
const MONTHLY = "MONTHLY";
const YEARLY = "YEARLY";
const SHIFT = "SHIFT";
const SKIP = "SKIP";
const NEVER = "NEVER";
const AFTER_GIVEN_DATE = "AFTER_GIVEN_DATE";
const REGULAR = "REGULAR";
const CARDIO = "CARDIO";
const CALISTHENICS = "CALISTHENICS";
const WEIGHT_TRAINING = "WEIGHT_TRAINING";
const NOT_TIMED = "NOT_TIMED";
const TIMED = "TIMED";

module.exports = {
  CATEGORY_ENUM: [REGULAR, CARDIO, CALISTHENICS, WEIGHT_TRAINING],
  RECURRENCE_ENUM: [DAILY, WEEKLY, MONTHLY, YEARLY],
  SCHEDULE_ENUM: [NOT_TIMED, TIMED],
  INVALID_DATE_STRATEGY_ENUM: [SHIFT, SKIP],
  autoRemove_ENUM: [NEVER, AFTER_GIVEN_DATE],
  CATEGORY: { REGULAR, CARDIO, CALISTHENICS, WEIGHT_TRAINING },
  RECURRENCE: { DAILY, WEEKLY, MONTHLY, YEARLY },
  SCHEDULE: { NOT_TIMED, TIMED },
  INVALID_DATE_STRATEGY: { SHIFT, SKIP },
  autoRemove: { NEVER, AFTER_GIVEN_DATE },
};
